`timescale 1ns/1ps
`default_nettype none

//==============================================================================
// video_timing_core
//------------------------------------------------------------------------------
// ROLE
//   Raster timing generator for a video scanout pipeline.
//
// HIGH-LEVEL PURPOSE
//   This module produces the fundamental timing signals needed by a
//   raster-oriented video system:
//
//     - pix_x      : current horizontal pixel position within the full line
//     - pix_y      : current vertical line position within the full frame
//     - de         : data-enable / active-video qualifier
//     - hsync      : horizontal synchronization pulse
//     - vsync      : vertical synchronization pulse
//     - frame_tick : one-cycle indicator of the frame origin
//
// CONCEPTUAL MODEL
//   A raster display is generated by scanning across a line from left to right,
//   then moving to the next line, and repeating until a full frame has been
//   traversed. This module models that process with two counters:
//
//     pix_x : horizontal position counter
//     pix_y : vertical position counter
//
//   Together, these counters define the current coordinate in the *full timing
//   raster*, not just the visible image region.
//
// IMPORTANT DISTINCTION
//   The raster contains more than the visible image.
//
//   Each line is divided into:
//
//     1) active video region
//     2) front porch
//     3) sync pulse
//     4) back porch
//
//   Similarly, each frame is divided into:
//
//     1) active video lines
//     2) vertical front porch
//     3) vertical sync pulse
//     4) vertical back porch
//
//   Therefore, pix_x and pix_y advance through the *entire timing envelope*,
//   not only the visible rectangle.
//
// WHY THIS MODULE EXISTS
//   Every downstream video block needs a consistent notion of:
//
//     - where the current pixel is
//     - whether that pixel lies in active video
//     - when line and frame boundaries occur
//
//   Without such a module, renderers and output serializers would have no
//   common timing reference.
//
// SIGNAL SEMANTICS
//   clk_vid
//     Video-domain pixel clock.
//     One increment of pix_x occurs per rising edge of this clock.
//
//   rst_vid
//     Active-high synchronous reset for the video timing domain.
//
//   pix_x
//     Horizontal timing coordinate, ranging from 0 to H_TOTAL-1.
//
//   pix_y
//     Vertical timing coordinate, ranging from 0 to V_TOTAL-1.
//
//   de
//     Data-enable signal.
//     High only when the current (pix_x, pix_y) lies inside the active visible
//     image region.
//
//   hsync
//     Horizontal synchronization pulse, polarity-controlled by HSYNC_POL.
//
//   vsync
//     Vertical synchronization pulse, polarity-controlled by VSYNC_POL.
//
//   frame_tick
//     High for one cycle when the coordinate is exactly the frame origin
//     (pix_x = 0, pix_y = 0).
//
// PARAMETER SEMANTICS
//   Horizontal timing:
//     H_ACTIVE : visible pixels per line
//     H_FP     : horizontal front porch
//     H_SYNC   : horizontal sync width
//     H_BP     : horizontal back porch
//
//   Vertical timing:
//     V_ACTIVE : visible lines per frame
//     V_FP     : vertical front porch
//     V_SYNC   : vertical sync height
//     V_BP     : vertical back porch
//
//   Sync polarity:
//     HSYNC_POL : if 1, hsync active region is high; if 0, active region is low
//     VSYNC_POL : if 1, vsync active region is high; if 0, active region is low
//
// DERIVED TOTALS
//   The full horizontal timing period is:
//
//       H_TOTAL = H_ACTIVE + H_FP + H_SYNC + H_BP
//
//   The full vertical timing period is:
//
//       V_TOTAL = V_ACTIVE + V_FP + V_SYNC + V_BP
//
//   These totals define the complete timing raster dimensions.
//
// RASTER ORDER
//   The module scans in row-major raster order:
//
//     (0,0), (1,0), (2,0), ..., (H_TOTAL-1,0),
//     then
//     (0,1), (1,1), ...
//
//   After the final coordinate:
//
//     (H_TOTAL-1, V_TOTAL-1)
//
//   the raster wraps back to:
//
//     (0,0)
//
// ACTIVE VIDEO INTERPRETATION
//   The visible image occupies only the rectangle:
//
//       0 <= pix_x < H_ACTIVE
//       0 <= pix_y < V_ACTIVE
//
//   Therefore:
//
//       de = 1
//
//   only inside that rectangle.
//
//   Outside that rectangle, the raster is traversing porches or sync intervals,
//   and de is low.
//
// SYNC PULSE INTERPRETATION
//   Horizontal sync is active during the horizontal interval:
//
//       H_ACTIVE + H_FP
//           <= pix_x
//           < H_ACTIVE + H_FP + H_SYNC
//
//   Vertical sync is active during the vertical interval:
//
//       V_ACTIVE + V_FP
//           <= pix_y
//           < V_ACTIVE + V_FP + V_SYNC
//
//   These are first computed as active-high internal windows:
//       hsync_int
//       vsync_int
//
//   Then output polarity is applied using HSYNC_POL and VSYNC_POL.
//
// FRAME TICK INTERPRETATION
//   frame_tick is asserted whenever:
//
//       pix_x == 0 && pix_y == 0
//
//   This corresponds to the frame origin.
//
//   In many systems, including this project, frame_tick is a highly important
//   synchronization event because it can be used to:
//
//     - latch new frame-stable state
//     - commit cross-domain snapshots
//     - increment frame counters
//     - coordinate overlays with raster boundaries
//
// RESET BEHAVIOR
//   On rst_vid assertion:
//
//       pix_x <= 0
//       pix_y <= 0
//
//   Therefore, reset places the timing generator at the raster origin.
//
// DESIGN PHILOSOPHY
//   This module intentionally keeps timing generation purely counter-based and
//   deterministic. It does not perform rendering; it only defines the timing
//   coordinate system in which rendering occurs.
//------------------------------------------------------------------------------
module video_timing_core #(
    //--------------------------------------------------------------------------
    // Horizontal timing parameters
    //--------------------------------------------------------------------------
    parameter integer H_ACTIVE   = 640,
    parameter integer H_FP       = 16,
    parameter integer H_SYNC     = 96,
    parameter integer H_BP       = 48,

    //--------------------------------------------------------------------------
    // Vertical timing parameters
    //--------------------------------------------------------------------------
    parameter integer V_ACTIVE   = 480,
    parameter integer V_FP       = 10,
    parameter integer V_SYNC     = 2,
    parameter integer V_BP       = 33,

    //--------------------------------------------------------------------------
    // Sync output polarity parameters
    //
    // If HSYNC_POL = 1, the active sync interval is driven high.
    // If HSYNC_POL = 0, the active sync interval is driven low.
    //
    // If VSYNC_POL = 1, the active sync interval is driven high.
    // If VSYNC_POL = 0, the active sync interval is driven low.
    //--------------------------------------------------------------------------
    parameter integer HSYNC_POL  = 0,
    parameter integer VSYNC_POL  = 0
)(
    //--------------------------------------------------------------------------
    // Video pixel clock.
    //
    // One horizontal timing step occurs per rising edge of this clock.
    //--------------------------------------------------------------------------
    input  wire        clk_vid,

    //--------------------------------------------------------------------------
    // Active-high synchronous video-domain reset.
    //
    // Resets the timing coordinates to the frame origin.
    //--------------------------------------------------------------------------
    input  wire        rst_vid,

    //--------------------------------------------------------------------------
    // Horizontal timing coordinate.
    //
    // Range:
    //   0 to H_TOTAL-1
    //--------------------------------------------------------------------------
    output reg  [11:0] pix_x,

    //--------------------------------------------------------------------------
    // Vertical timing coordinate.
    //
    // Range:
    //   0 to V_TOTAL-1
    //--------------------------------------------------------------------------
    output reg  [11:0] pix_y,

    //--------------------------------------------------------------------------
    // Data-enable / active-video flag.
    //
    // High only inside the visible image region.
    //--------------------------------------------------------------------------
    output wire        de,

    //--------------------------------------------------------------------------
    // Horizontal synchronization output.
    //--------------------------------------------------------------------------
    output wire        hsync,

    //--------------------------------------------------------------------------
    // Vertical synchronization output.
    //--------------------------------------------------------------------------
    output wire        vsync,

    //--------------------------------------------------------------------------
    // One-cycle frame-origin indicator.
    //--------------------------------------------------------------------------
    output wire        frame_tick
);

    //==========================================================================
    // Total raster dimensions
    //--------------------------------------------------------------------------
    // H_TOTAL:
    //   Total number of pixel-clock intervals per line, including visible
    //   region, porches, and sync.
    //
    // V_TOTAL:
    //   Total number of lines per frame, including visible region, porches, and
    //   sync.
    //==========================================================================
    localparam integer H_TOTAL = H_ACTIVE + H_FP + H_SYNC + H_BP;
    localparam integer V_TOTAL = V_ACTIVE + V_FP + V_SYNC + V_BP;

    //==========================================================================
    // Raster coordinate counters
    //--------------------------------------------------------------------------
    // Step-by-step sequential behavior on each rising edge of clk_vid:
    //
    //   Case 1: rst_vid is asserted
    //     1) Clear pix_x to 0
    //     2) Clear pix_y to 0
    //
    //     Engineering meaning:
    //       Reset returns the raster generator to the frame origin.
    //
    //   Case 2: pix_x has reached the final horizontal position of the line
    //           (pix_x == H_TOTAL - 1)
    //     1) Wrap pix_x back to 0, because the current line is finished
    //     2) Then decide what to do with pix_y:
    //
    //        Subcase 2a: pix_y has also reached the final line of the frame
    //                    (pix_y == V_TOTAL - 1)
    //          - wrap pix_y back to 0
    //
    //          Meaning:
    //            The full frame is complete, so restart at the top-left timing
    //            coordinate of the next frame.
    //
    //        Subcase 2b: pix_y has not yet reached the final line
    //          - increment pix_y by one
    //
    //          Meaning:
    //            Advance from the end of the current line to the start of the
    //            next line.
    //
    //   Case 3: pix_x has not yet reached the end of the line
    //     1) Increment pix_x by one
    //     2) Leave pix_y unchanged
    //
    //     Meaning:
    //       Advance one pixel position to the right within the current line.
    //
    // Resulting raster traversal:
    //   The counters move left-to-right across a line and top-to-bottom across
    //   the frame, then wrap back to the origin.
    //==========================================================================
    always @(posedge clk_vid) begin
        if (rst_vid) begin
            pix_x <= 12'd0;
            pix_y <= 12'd0;
        end else if (pix_x == H_TOTAL-1) begin
            pix_x <= 12'd0;
            if (pix_y == V_TOTAL-1)
                pix_y <= 12'd0;
            else
                pix_y <= pix_y + 12'd1;
        end else begin
            pix_x <= pix_x + 12'd1;
        end
    end

    //==========================================================================
    // Active-video qualification
    //--------------------------------------------------------------------------
    // de is high only when the current timing coordinate lies within the
    // visible image rectangle.
    //
    // Horizontal visible range:
    //   0 <= pix_x < H_ACTIVE
    //
    // Vertical visible range:
    //   0 <= pix_y < V_ACTIVE
    //
    // Therefore:
    //   de is the logical AND of those two visibility conditions.
    //
    // Engineering meaning:
    //   Downstream renderers can use de to determine whether the current
    //   coordinate corresponds to a visible pixel that should be sent as image
    //   data, rather than a porch or sync interval.
    //==========================================================================
    assign de = (pix_x < H_ACTIVE) && (pix_y < V_ACTIVE);

    //==========================================================================
    // Internal active-high sync windows
    //--------------------------------------------------------------------------
    // hsync_int:
    //   Indicates that pix_x lies inside the horizontal sync interval.
    //
    // Horizontal sync starts after:
    //   - all active pixels, plus
    //   - the horizontal front porch
    //
    // It remains active for H_SYNC pixel clocks.
    //
    // Concretely:
    //   start = H_ACTIVE + H_FP
    //   stop  = H_ACTIVE + H_FP + H_SYNC
    //
    // The interval is half-open:
    //   start <= pix_x < stop
    //
    // vsync_int:
    //   Indicates that pix_y lies inside the vertical sync interval.
    //
    // Vertical sync starts after:
    //   - all active lines, plus
    //   - the vertical front porch
    //
    // It remains active for V_SYNC lines.
    //
    // Concretely:
    //   start = V_ACTIVE + V_FP
    //   stop  = V_ACTIVE + V_FP + V_SYNC
    //
    // The interval is also half-open:
    //   start <= pix_y < stop
    //==========================================================================
    wire hsync_int = (pix_x >= (H_ACTIVE + H_FP)) &&
                     (pix_x <  (H_ACTIVE + H_FP + H_SYNC));

    wire vsync_int = (pix_y >= (V_ACTIVE + V_FP)) &&
                     (pix_y <  (V_ACTIVE + V_FP + V_SYNC));

    //==========================================================================
    // Sync polarity application
    //--------------------------------------------------------------------------
    // The internal sync windows hsync_int and vsync_int are defined as active-
    // high timing intervals.
    //
    // The output signals hsync and vsync are then produced by applying the
    // configured polarity:
    //
    //   If HSYNC_POL = 1:
    //       hsync = hsync_int
    //   Else:
    //       hsync = ~hsync_int
    //
    //   If VSYNC_POL = 1:
    //       vsync = vsync_int
    //   Else:
    //       vsync = ~vsync_int
    //
    // This makes the timing-window definition independent of output polarity.
    //==========================================================================
    assign hsync = HSYNC_POL ? hsync_int : ~hsync_int;
    assign vsync = VSYNC_POL ? vsync_int : ~vsync_int;

    //==========================================================================
    // Frame-origin pulse
    //--------------------------------------------------------------------------
    // frame_tick is high exactly when the raster coordinate is:
    //
    //   pix_x = 0
    //   pix_y = 0
    //
    // Since the counters visit that coordinate once per frame, frame_tick
    // becomes a one-cycle "start-of-frame" indicator.
    //
    // Engineering meaning:
    //   This is extremely useful for frame-coherent state updates, counters,
    //   and renderer synchronization.
    //==========================================================================
    assign frame_tick = (pix_x == 12'd0) && (pix_y == 12'd0);

endmodule

`default_nettype wire