`timescale 1ns/1ps
`default_nettype none

//==============================================================================
// clk_wiz_hdmi_640x480
//------------------------------------------------------------------------------
// PURPOSE
//   Generate two clocks from a 100 MHz board reference clock for a simple
//   640x480-class HDMI/DVI transmit path:
//
//     1) clk_out1 = pixel clock domain
//        Nominally 25.000 MHz in this implementation
//
//     2) clk_out2 = high-speed TMDS serializer clock domain
//        5x the pixel clock, nominally 125.000 MHz here
//
//   The module also exports `locked`, which indicates that the MMCM has
//   achieved phase/frequency lock and that the generated clocks are considered
//   stable for downstream synchronous logic.
//
// SYSTEM ROLE
//   In a minimal FPGA HDMI/DVI pipeline, two clock rates are often required:
//
//     - A pixel-rate clock for timing generation, active-video traversal, and
//       RGB pixel production.
//
//     - A higher-rate serialization clock used by the TMDS transmit path.
//
//   For a 640x480-style bring-up path, many practical designs use:
//
//       pixel clock      = 25.000 MHz
//       serializer clock = 125.000 MHz = 5 * 25.000 MHz
//
//   This is slightly different from the exact VGA nominal pixel clock
//   (25.175 MHz), but many displays tolerate 25.000 MHz for first-light and
//   basic debug operation.
//
// ASSUMPTIONS
//   - Input reference clock clk_in1 is 100.000 MHz.
//   - The target device supports MMCME2_BASE.
//   - A 25.000 MHz pixel clock is acceptable for the intended monitor/display.
//   - The downstream TMDS path is architected around a 5x serialization clock.
//
// INPUTS
//   clk_in1
//     Primary board clock input, assumed to be 100.000 MHz.
//
//   reset
//     MMCM reset input. When asserted, the MMCM is forced out of lock and will
//     restart lock acquisition once reset is released.
//
// OUTPUTS
//   clk_out1
//     Buffered pixel-domain clock generated by the MMCM.
//
//   clk_out2
//     Buffered 5x TMDS serializer-domain clock generated by the MMCM.
//
//   locked
//     MMCM lock indication. Downstream reset-generation logic typically uses
//     this signal to hold video logic in reset until the clocks are stable.
//
// CLOCKING TOPOLOGY
//   The clock path is:
//
//       clk_in1
//         -> BUFG input buffer
//         -> MMCM
//         -> BUFG feedback buffer for closed-loop feedback
//         -> BUFG pixel output
//         -> BUFG 5x serializer output
//
//   The use of BUFG on both the input path and generated output paths ensures
//   low-skew distribution on the global clock network.
//
// MMCM NUMERICAL CONFIGURATION
//   Given:
//       Fin = 100.000 MHz
//
//   MMCM parameters:
//       DIVCLK_DIVIDE   = 1
//       CLKFBOUT_MULT_F = 10.000
//
//   Therefore the VCO frequency is:
//
//       Fvco = Fin * CLKFBOUT_MULT_F / DIVCLK_DIVIDE
//            = 100.000 MHz * 10.000 / 1
//            = 1000.000 MHz
//
//   Output clocks:
//
//       clk_out1 via CLKOUT0_DIVIDE_F = 40.000
//       Fout0 = Fvco / 40.000
//             = 1000.000 / 40.000
//             = 25.000 MHz
//
//       clk_out2 via CLKOUT1_DIVIDE = 8
//       Fout1 = Fvco / 8
//             = 1000.000 / 8
//             = 125.000 MHz
//
//   Since 125.000 MHz = 5 * 25.000 MHz, the second output is appropriate for a
//   5x TMDS serialization path.
//
// IMPORTANT DESIGN LIMITATION
//   This module does not generate the exact historical VGA nominal pixel clock
//   of 25.175 MHz. Instead it generates 25.000 MHz for implementation
//   simplicity and practical display tolerance.
//
//   If exact 25.175 MHz is required, the MMCM multiplication/division ratios
//   must be recalculated and timing constraints updated accordingly.
//
// RESET / LOCK SEMANTICS
//   - When `reset` is asserted, the MMCM is reset.
//   - While the MMCM is not locked, downstream logic should generally be held
//     in reset.
//   - `locked` should therefore be treated as a clock-stability qualifier, not
//     as a general-purpose status LED signal only.
//
// SYNTHESIS / IMPLEMENTATION NOTES
//   - This module is device-primitive-specific because it instantiates
//     MMCME2_BASE and BUFG primitives.
//   - It is therefore intended for Xilinx 7-series style toolflows.
//   - Timing constraints should reference the generated clocks so the tools
//     correctly understand the pixel and TMDS clock domains.
//
//==============================================================================
module clk_wiz_hdmi_640x480 (
    input  wire clk_in1,
    input  wire reset,
    output wire clk_out1,
    output wire clk_out2,
    output wire locked
);

    //--------------------------------------------------------------------------
    // Input clock buffering
    //--------------------------------------------------------------------------
    // The external board clock is first placed onto a global clock buffer.
    //
    // Why this stage exists:
    //   1) It moves the raw clock input onto the FPGA's dedicated global clock
    //      network.
    //   2) It reduces skew for downstream clocking resources.
    //   3) It provides a clean clock source for the MMCM input.
    //
    // The buffered result, clk_in1_bufg, is the version of the reference clock
    // actually presented to the MMCM.
    //--------------------------------------------------------------------------
    wire clk_in1_bufg;

    BUFG u_bufg_in (
        .I(clk_in1),
        .O(clk_in1_bufg)
    );

    //--------------------------------------------------------------------------
    // MMCM internal interconnect signals
    //--------------------------------------------------------------------------
    // clkfb / clkfb_bufg
    //   Feedback path required by the MMCM closed-loop frequency synthesis.
    //
    // clk_pix_mmcm
    //   Raw pixel clock coming directly from the MMCM before final BUFG output
    //   distribution.
    //
    // clk_tmds_5x_mmcm
    //   Raw 5x serializer clock from the MMCM before final BUFG output
    //   distribution.
    //--------------------------------------------------------------------------
    wire clkfb;
    wire clkfb_bufg;

    wire clk_pix_mmcm;
    wire clk_tmds_5x_mmcm;

    //--------------------------------------------------------------------------
    // MMCM instance
    //--------------------------------------------------------------------------
    // This primitive performs clock multiplication and division.
    //
    // Step-by-step arithmetic:
    //
    //   Input clock:
    //       Fin = 100.000 MHz
    //
    //   Feedback multiplication:
    //       Multiplier = 10.000
    //
    //   Input division:
    //       DIVCLK_DIVIDE = 1
    //
    //   Therefore:
    //       Fvco = 100.000 * 10.000 / 1 = 1000.000 MHz
    //
    //   Output clock 0:
    //       Divide = 40.000
    //       Fout0  = 1000.000 / 40.000 = 25.000 MHz
    //
    //   Output clock 1:
    //       Divide = 8
    //       Fout1  = 1000.000 / 8 = 125.000 MHz
    //
    // The remaining unused MMCM output dividers/phases/duty cycles are filled
    // with explicit values for completeness and to avoid ambiguity.
    //
    // STARTUP_WAIT = "FALSE"
    //   Means the primitive itself does not hold global startup waiting for
    //   lock. Instead, downstream reset logic should use `locked`.
    //--------------------------------------------------------------------------
    MMCME2_BASE #(
        .BANDWIDTH("OPTIMIZED"),

        // Reference clock period in ns for 100.000 MHz
        .CLKIN1_PERIOD      (10.000),

        // VCO synthesis parameters
        .DIVCLK_DIVIDE      (1),
        .CLKFBOUT_MULT_F    (10.000),

        // Generated output dividers
        .CLKOUT0_DIVIDE_F   (40.000), // 25.000 MHz pixel clock
        .CLKOUT1_DIVIDE     (8),      // 125.000 MHz = 5x pixel clock
        .CLKOUT2_DIVIDE     (1),
        .CLKOUT3_DIVIDE     (1),
        .CLKOUT4_DIVIDE     (1),
        .CLKOUT5_DIVIDE     (1),
        .CLKOUT6_DIVIDE     (1),

        // Output phases
        .CLKOUT0_PHASE      (0.000),
        .CLKOUT1_PHASE      (0.000),
        .CLKOUT2_PHASE      (0.000),
        .CLKOUT3_PHASE      (0.000),
        .CLKOUT4_PHASE      (0.000),
        .CLKOUT5_PHASE      (0.000),
        .CLKOUT6_PHASE      (0.000),

        // Output duty cycles
        .CLKOUT0_DUTY_CYCLE (0.500),
        .CLKOUT1_DUTY_CYCLE (0.500),
        .CLKOUT2_DUTY_CYCLE (0.500),
        .CLKOUT3_DUTY_CYCLE (0.500),
        .CLKOUT4_DUTY_CYCLE (0.500),
        .CLKOUT5_DUTY_CYCLE (0.500),
        .CLKOUT6_DUTY_CYCLE (0.500),

        .STARTUP_WAIT("FALSE")
    ) u_mmcm (
        // Buffered reference clock input
        .CLKIN1   (clk_in1_bufg),

        // External reset into the MMCM
        .RST      (reset),

        // Closed-loop feedback path
        .CLKFBIN  (clkfb_bufg),
        .CLKFBOUT (clkfb),

        // Generated output clocks
        .CLKOUT0  (clk_pix_mmcm),
        .CLKOUT1  (clk_tmds_5x_mmcm),
        .CLKOUT2  (),
        .CLKOUT3  (),
        .CLKOUT4  (),
        .CLKOUT5  (),
        .CLKOUT6  (),

        // Lock indicator
        .LOCKED   (locked),

        // Power-down disabled
        .PWRDWN   (1'b0)
    );

    //--------------------------------------------------------------------------
    // Feedback clock buffering
    //--------------------------------------------------------------------------
    // The MMCM feedback output is routed through a BUFG and returned to
    // CLKFBIN. This forms the compensated global-buffered feedback loop used by
    // the MMCM to maintain stable synthesized output frequencies and phases.
    //--------------------------------------------------------------------------
    BUFG u_bufg_fb (
        .I(clkfb),
        .O(clkfb_bufg)
    );

    //--------------------------------------------------------------------------
    // Output clock buffering: pixel domain
    //--------------------------------------------------------------------------
    // The raw MMCM pixel clock is promoted onto the global clock network before
    // being exported as clk_out1.
    //
    // This clock is expected to drive:
    //   - horizontal/vertical timing counters
    //   - active-video coordinate generation
    //   - pixel-generation logic
    //   - pre-serialization video-domain pipelines
    //--------------------------------------------------------------------------
    BUFG u_bufg_pix (
        .I(clk_pix_mmcm),
        .O(clk_out1)
    );

    //--------------------------------------------------------------------------
    // Output clock buffering: 5x TMDS serializer domain
    //--------------------------------------------------------------------------
    // The raw high-speed MMCM output is promoted onto the global clock network
    // before export as clk_out2.
    //
    // This clock is expected to drive:
    //   - TMDS serializer logic
    //   - OSERDES staging logic
    //   - any transmit-side gearboxing that requires the 5x clock
    //--------------------------------------------------------------------------
    BUFG u_bufg_tmds_5x (
        .I(clk_tmds_5x_mmcm),
        .O(clk_out2)
    );

endmodule

`default_nettype wire